
obj-$(CONFIG_LCD_TRULY_TFT240240_2_E) += lcd-truly_tft240240_2_e.o
obj-$(CONFIG_LCD_KFM701A21_1A)			+= lcd-kfm701a21_1a.o
obj-$(CONFIG_LCD_DK_ST7789H2)         += dk_st7789h2.o

obj-$(CONFIG_H139BLN01_IC_SSD2805C)         += h139bln01_ic_ssd2805c.o
obj-$(CONFIG_LCD_LH154Q01_IC_SSD2805C)      += lh154q01.o
obj-$(CONFIG_LCD_H320QN01_IC_SSD2805C)      += h320qn01.o
obj-$(CONFIG_MOTO320X290_IC_FPGA)         += moto320X290_ic_fpga.o
obj-$(CONFIG_LCD_BOEH0154_IC)         += boe_h0154.o
