#
# Makefile for the touchscreen drivers.
#

# Each configuration option enables a list of files.


##########-ingenic-touchscreen-###########

#obj-$(CONFIG_TOUCHSCREEN_JZ_GT801)	+= tsc_gt801.o
obj-y	+= gt1x.o gt1x_generic.o gt1x_update.o gt1x_tools.o gt1x_extents.o

