
obj-$(CONFIG_LCD_TRULY_TFT240240_2_E) += lcd-truly_tft240240_2_e.o
obj-$(CONFIG_LCD_KFM701A21_1A)			+= lcd-kfm701a21_1a.o
obj-$(CONFIG_LCD_DK_ST7789H2)         += dk_st7789h2.o
#add by zxj
obj-$(CONFIG_H139BLN01_IC_SSD2805C)         += h139bln01_ic_ssd2805c.o
obj-$(CONFIG_LCD_LS030Y3D_IC_SSD1963) += ls030y3d_ic_ssd1963.o